name: Publish to TestPyPI

on:
  push:
    branches:
      - main  # Or any other branch you want to trigger the upload from
    tags:
      - 'v*'  # This ensures the action runs on version tags like v1.0.0

jobs:
  testpypi-publish:
    name: Upload release to TestPyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v2

    # Add steps to build your package distributions here
    # For example, using setuptools:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build and check package
      run: |
        python -m pip install --upgrade build twine
        python -m build
        twine check dist/*

    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
